import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function freePort(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
test('Local sandbox HTTP API integration',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pact-test-')),file=path.join(dir,'sandbox.json'),port=await freePort(),url=`http://127.0.0.1:${port}`;
 let child;
 async function start(){child=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port),DATA_FILE:file,ESCROW_MODE:'sandbox'},stdio:'ignore'});for(let i=0;i<60;i++){try{const res=await fetch(url+'/api/health');if(res.ok)return;}catch{}await delay(50);}throw new Error('Server startup timed out');}
 async function stop(){if(child&&child.exitCode===null){const done=new Promise(r=>child.once('exit',r));child.kill();await done;}}
 const getState=async()=> (await (await fetch(url+'/api/state')).json()).state;
 const post=async(data,headers={})=>{const res=await fetch(url+'/api/command',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(data)});return {status:res.status,body:await res.json()};};
 await start();
 try{
  await t.test('health explicitly reports sandbox with no real funds',async()=>{const x=await (await fetch(url+'/api/health')).json();assert.deepEqual(x,{ok:true,mode:'sandbox',realFunds:false});});
  await t.test('HTML, stylesheet, and shared model are served with correct types',async()=>{for(const [route,type] of [['/','text/html'],['/styles.css','text/css'],['/domain.mjs','text/javascript'],['/agreement.mjs','text/javascript']]){const x=await fetch(url+route);assert.equal(x.status,200);assert.match(x.headers.get('content-type'),new RegExp(type));}const x=await fetch(url+'/server.mjs');assert.equal(x.status,404);});
  await t.test('untrusted web origin is refused',async()=>{const x=await post({},{Origin:'https://attacker.example'});assert.equal(x.status,403);});
  await t.test('unknown demo identity is not granted a role',async()=>{const x=await post({actorId:'intruder',command:'post_brief',payload:{},idempotencyKey:'unknown-identity-test'});assert.equal(x.status,403);});
  const payload={actorId:'buyer',command:'post_brief',payload:{title:'An integration test project',category:'Design',budget:'250',description:'Create an editable set of designs with the agreed delivery formats and documented acceptance requirements.'},idempotencyKey:'repeatable-test-command'};
  let briefId;
  await t.test('idempotent retries create only one record',async()=>{const a=await post(payload),b=await post(payload);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(a.body.result,b.body.result);briefId=a.body.result;assert.equal(b.body.replayed,true);assert.equal((await getState()).briefs.filter(x=>x.id===briefId).length,1);});
  const durablePayload={actorId:'buyer',command:'post_brief',payload:{title:'Durable replay integration brief',category:'Design',budget:'251',description:'A fictional brief used to verify that old idempotency records remain replayable after many later commands.'},idempotencyKey:'durable-replay-key'};
  let durableId;
  await t.test('idempotency survives more than one thousand later commands',async()=>{const first=await post(durablePayload);assert.equal(first.status,200);durableId=first.body.result;for(let i=0;i<1001;i++){const x=await post({actorId:'buyer',command:'post_brief',payload:{title:`Later fictional brief ${i}`,category:'Design',budget:'100',description:'A later synthetic command for durable idempotency testing and no real funds.'},idempotencyKey:`durable-later-${String(i).padStart(4,'0')}`});assert.equal(x.status,200);}const replay=await post(durablePayload);assert.equal(replay.status,200);assert.equal(replay.body.replayed,true);assert.equal(replay.body.result,durableId);assert.equal((await getState()).briefs.filter(x=>x.id===durableId).length,1);});
  await t.test('reused key with altered content is refused',async()=>{const x=await post({...payload,payload:{...payload.payload,budget:'999'}});assert.equal(x.status,409);});
  await t.test('wallet substitution cannot be smuggled through command payload',async()=>{const s=await getState(),o=s.orders[0];const x=await post({actorId:o.buyerId,command:'add_message',payload:{orderId:o.id,expectedVersion:o.version,text:'This is a test message.',sellerWallet:'ATTACKER'},idempotencyKey:'reject-wallet-substitution'});assert.equal(x.status,400);assert.match(x.body.error,/Unsupported field/);});
  await t.test('stale writes return a conflict instead of overwriting state',async()=>{const s=await getState(),o=s.orders[0];const x=await post({actorId:o.buyerId,command:'add_message',payload:{orderId:o.id,expectedVersion:0,text:'This stale write must not be applied.'},idempotencyKey:'stale-write-test'});assert.equal(x.status,409);});
  await t.test('payroll command responses are actor-scoped',async()=>{const atomicAdd=await post({actorId:'buyer',command:'payroll_add_staff',payload:{name:'Atomic API Payee',role:'Ops',salary:'11',wallet:'demo-atomic-api'},idempotencyKey:'api-payroll-atomic-add'});assert.equal(atomicAdd.status,200);const atomic=await post({actorId:'buyer',command:'payroll_authorize_plan',payload:{name:'Atomic API payroll',budget:'11',months:1,mode:'manual',startDate:'2026-10-30',timezone:'UTC',staffIds:[atomicAdd.body.result],acknowledge:true},idempotencyKey:'api-payroll-atomic-authorize'});assert.equal(atomic.status,200);assert.equal(atomic.body.result.status,'approved');const add=await post({actorId:'buyer',command:'payroll_add_staff',payload:{name:'API Payee',role:'Ops',salary:'10',wallet:'demo-api-payee'},idempotencyKey:'api-payroll-add'});assert.equal(add.status,200);const staffId=add.body.result;const create=await post({actorId:'buyer',command:'payroll_create_plan',payload:{name:'API payroll',budget:'10',months:1,mode:'manual',startDate:'2026-10-30',timezone:'UTC',staffIds:[staffId]},idempotencyKey:'api-payroll-create'});assert.equal(create.status,200);const planId=create.body.result;for(const [command,payload,key] of [['payroll_preview_plan',{planId},'api-payroll-preview'],['payroll_fund_plan',{planId,amount:'10'},'api-payroll-fund'],['payroll_submit_plan',{planId},'api-payroll-submit']]){const x=await post({actorId:'buyer',command,payload,idempotencyKey:key});assert.equal(x.status,200);}const approved=await post({actorId:'buyer',command:'payroll_approve_plan',payload:{planId},idempotencyKey:'api-payroll-approve'});assert.equal(approved.status,200);assert.deepEqual(Object.keys(approved.body.state.payrollByUser),['buyer']);assert.equal(approved.body.state.payrollByUser.buyer.runs.length,2);});
  await t.test('payroll snapshot endpoint hydrates an account without exposing it publicly',async()=>{const publicState=await (await fetch(url+'/api/state')).json();assert.equal(Object.prototype.hasOwnProperty.call(publicState.state,'payrollByUser'),false);const snapshot=await fetch(url+'/api/payroll?actorId=buyer');assert.equal(snapshot.status,200);const body=await snapshot.json();assert.equal(body.actorId,'buyer');assert.equal(body.mode,'sandbox');assert.equal(body.payroll.runs.length,2);assert.equal(body.summary.activeStaff,2);assert.equal(body.summary.reserved,'21');assert.equal(body.summary.disbursed,'0');assert.equal(body.summary.remaining,'21');assert.equal(body.summary.nextDueAt,'2026-10-30T09:00:00.000Z');assert.equal(body.summary.nextPeriod,'2026-10-30');assert.equal(body.summary.nextTimezone,'UTC');const unknown=await fetch(url+'/api/payroll?actorId=intruder');assert.equal(unknown.status,403);});
  await t.test('committed data survives process restart',async()=>{await stop();await start();assert.ok((await getState()).briefs.find(x=>x.id===briefId));const payroll=await fetch(url+'/api/payroll?actorId=buyer');assert.equal(payroll.status,200);assert.equal((await payroll.json()).payroll.runs.length,2);});
 }finally{await stop();fs.rmSync(dir,{recursive:true,force:true});}
});

test('A live-money mode is rejected on startup',async()=>{
 const child=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,ESCROW_MODE:'mainnet'},stdio:['ignore','ignore','pipe']});let err='';child.stderr.on('data',c=>err+=c);const code=await new Promise(r=>child.on('exit',r));assert.notEqual(code,0);assert.match(err,/SANDBOX ONLY/);
});
