import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as D from '../src/universal-domain.mjs';
import {createEmptyState,totalFunds} from '../src/domain.mjs';
import {migrateState} from '../src/state-migrations.mjs';
const NOW=1800000000000, criteria=['Deliver all editable source files as agreed'], scope='A documented, responsive website with all editable source files and working validation.';
function harness(asset){let s=createEmptyState(NOW);const run=(who,cmd,p,now=NOW)=>{let o=D.applyCommand(s,who,cmd,p,{now});s=o.state;return o.result;};const id=run('buyer','create_order',{sellerId:'maya',title:'A complete two-asset website',amount:'1000',asset,scope,criteria,requirements:scope,days:7,revisions:1,acceptance:'manual',milestones:false});const order=()=>s.orders.find(o=>o.id===id);const act=(who,cmd,p={},now=NOW)=>run(who,cmd,{orderId:id,expectedVersion:order().version,...p},now);const ms=(who,cmd,p={})=>act(who,cmd,{milestoneId:order().milestones[0].id,...p});act('maya','accept_order');act('buyer','fund_order');return {get s(){return s},run,order,act,ms};}
for(const asset of D.ASSET_CODES){const other=asset==='USDC'?'USDT':'USDC';
 test(`${asset}: funding, split, refund and fees preserve the other ledger`,()=>{const t=harness(asset);assert.equal(t.s.users[0].balances[asset],D.units('23970'));assert.equal(t.s.users[0].balances[other],D.units('25000'));t.ms('maya','propose_terms',{kind:'settle',amount:'600',scope,days:0});t.ms('buyer','accept_terms',{proposalId:t.order().milestones[0].proposal.id});assert.equal(t.s.users[0].balances[asset],D.units('24382'));assert.equal(t.s.users.find(x=>x.id==='maya').balances[asset],D.units('25600'));assert.equal(t.s.treasury.balances[asset].commission,D.units('18'));assert.deepEqual(t.s.treasury.balances[other],{commission:'0',disputeFees:'0'});for(const a of D.ASSET_CODES)assert.equal(totalFunds(t.s,a),t.s.initialFundsByAsset[a]);});
 test(`${asset}: dispute/refund charges initiator only in order asset`,()=>{const t=harness(asset);t.ms('buyer','open_dispute',{reason:scope,acknowledgeFee:true});t.ms('reviewer','resolve_refund',{reason:scope});assert.equal(t.s.users[0].balances[asset],D.units('24950'));assert.equal(t.s.users[0].balances[other],D.units('25000'));assert.equal(t.s.treasury.balances[asset].disputeFees,D.units('50'));assert.equal(t.s.treasury.balances[asset].commission,'0');D.assertInvariants(t.s);});
 test(`${asset}: amendments preserve asset and conserve each ledger`,()=>{const t=harness(asset);t.ms('maya','propose_terms',{kind:'amend',amount:'333.333333',scope,days:5});t.ms('buyer','accept_terms',{proposalId:t.order().milestones[0].proposal.id});t.ms('maya','submit_delivery',{text:scope,evidence:scope});t.ms('buyer','approve_delivery',{criteriaAccepted:true});assert.equal(t.order().asset,asset);assert.equal(t.order().snapshot.asset,asset);assert.equal(t.order().token,D.DEMO_TOKENS[asset]);assert.equal(t.s.users[0].balances[other],D.units('25000'));D.assertInvariants(t.s);});
 test(`${asset}: existing order cannot switch asset, token, amount or destination`,()=>{const t=harness(asset);for(const extra of [{asset:other},{token:D.DEMO_TOKENS[other]},{sellerWallet:'attacker'},{amount:'1'}]){const before=JSON.stringify(t.s);assert.throws(()=>t.act('buyer','add_message',{text:scope,...extra}));assert.equal(JSON.stringify(t.s),before);}const tamper=structuredClone(t.s);tamper.orders[0].asset=other;assert.throws(()=>D.assertInvariants(tamper,t.s));});
 test(`${asset}: independently quoted products snapshot selected values`,()=>{let s=D.createSeedState(NOW);const l=s.listings.find(x=>x.kind==='goods');l.packages[0].prices={USDC:D.units('100'),USDT:D.units('120')};l.shippingPrices={USDC:D.units('10'),USDT:D.units('20')};let out=D.applyCommand(s,'buyer','purchase_product',{listingId:l.id,asset,quantity:2,requirements:scope,deliveryReference:'Fictional test location',agreeInspection:true,agreeFees:true},{now:NOW});s=out.state;const o=s.orders.find(x=>x.id===out.result);assert.equal(o.commerce.total,D.units(asset==='USDC'?'210':'260'));assert.equal(o.commerce.asset,asset);const orderId=o.id;for(const [who,cmd] of [[o.sellerId,'accept_order'],['buyer','fund_order']]){s=D.applyCommand(s,who,cmd,{orderId,expectedVersion:s.orders.find(x=>x.id===orderId).version},{now:NOW}).state;}D.assertInvariants(s);});
 test(`${asset}: brief quote and agreement keep brief asset`,()=>{let s=createEmptyState(NOW);let o=D.applyCommand(s,'buyer','post_brief',{title:'A precisely scoped website',category:'Development',budget:'111',description:scope,asset},{now:NOW});s=o.state;const id=o.result;o=D.applyCommand(s,'maya','quote_brief',{briefId:id,amount:'123.000001',scope,days:7},{now:NOW});s=o.state;assert.equal(s.briefs[0].asset,asset);assert.equal(s.briefs[0].proposals[0].asset,asset);assert.throws(()=>D.applyCommand(s,'samir','quote_brief',{briefId:id,amount:'1',scope,days:7,asset:other}));});
}
test('USDT-only packages never silently fall back or convert',()=>{const s=createEmptyState(NOW),l=s.listings[0];for(const p of l.packages)p.prices={USDT:D.units('500')};const payload={listingId:l.id,packageIndex:0,requirements:scope,acceptance:'manual'};assert.throws(()=>D.applyCommand(s,'buyer','create_order',payload),/USDC/);assert.throws(()=>D.applyCommand(s,'buyer','create_order',{...payload,asset:'USDC'}),/quote/);const o=D.applyCommand(s,'buyer','create_order',{...payload,asset:'USDT'});assert.equal(o.state.orders[0].milestones[0].originalAmount,D.units('500'));});
test('Unsupported or wrong-case assets and scalar v3 aliases are rejected atomically',()=>{const t=harness('USDT');for(const a of ['BTC','usdt','USD',null,3])assert.throws(()=>t.run('buyer','post_brief',{title:'A precisely scoped website',category:'Development',budget:'111',description:scope,asset:a}));for(const edit of [s=>s.users[0].balance='0',s=>s.treasury.commission='0',s=>s.initialFunds='0',s=>s.listings[0].packages[0].price='100',s=>s.orders[0].feeBps=0]){let s=structuredClone(t.s);edit(s);assert.throws(()=>D.assertInvariants(s));}});
for(const fixture of ['legacy-base','legacy-universal'])test(`${fixture}: pure deterministic migration preserves evidence, supply and replay journal`,()=>{const old=JSON.parse(fs.readFileSync(new URL(`./fixtures/${fixture}.json`,import.meta.url),'utf8').replace(/^\uFEFF/,''));old.processedCommands=[{key:'previous-idempotency',signature:'unchanged-signature',result:'existing-id'}];const before=JSON.stringify(old),s=migrateState(old);assert.equal(JSON.stringify(old),before);assert.deepEqual(migrateState(s),s);assert.equal(s.schemaVersion,3);assert.deepEqual(s.initialFundsByAsset,{USDC:old.initialFunds,USDT:'0'});assert.deepEqual(s.processedCommands,old.processedCommands);for(let i=0;i<s.orders.length;i++){assert.equal(s.orders[i].asset,'USDC');assert.deepEqual(s.orders[i].snapshot,old.orders[i].snapshot);assert.deepEqual(s.orders[i].events,old.orders[i].events);assert.deepEqual(s.orders[i].commerce,old.orders[i].commerce);}for(const u of s.users){assert.equal(u.balances.USDT,'0');assert.ok(!('balance'in u));}for(const l of s.listings)for(const p of l.packages)assert.deepEqual(Object.keys(p.prices),['USDC']);D.assertInvariants(s);});
test('Migration rejects corrupted or mixed data without mutating the source',()=>{const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/legacy-universal.json',import.meta.url),'utf8').replace(/^\uFEFF/,''));for(const edit of [s=>s.users[0].balance='1.5',s=>s.users[0].balance='01',s=>s.users[0].balance=12,s=>s.users[0].balance='0',s=>s.initialFundsByAsset={USDC:'0',USDT:'0'},s=>s.listings[0].packages[0].prices={USDC:'1'},s=>s.listings.find(l=>l.kind==='goods').shippingPrices={USDC:'0'},s=>s.orders[0].asset='USDT',s=>s.orders[0].token=D.DEMO_TOKENS.USDT,s=>s.mode='mainnet',s=>s.schemaVersion=99,s=>s.version=0]){const s=structuredClone(fixture);edit(s);const before=JSON.stringify(s);assert.throws(()=>migrateState(s),{code:'MIGRATION_ERROR'});assert.equal(JSON.stringify(s),before);}});
