[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_global = "EZ2xS5M9Ras2eJXpe1cY73q6KvQxVuY12S1eVNcBEB6S"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
