/** Product taxonomy and versioned workflow templates. Not a promise of legal eligibility. */
export const CATEGORY_GROUPS = ['Physical products', 'Professional services', 'Business agreements', 'Digital handovers'];
export const TAXONOMY = [
  {id:'furniture',name:'Furniture & home',group:'Physical products',icon:'home',examples:'Furniture, lighting, decor, custom cabinetry',template:'goods',checks:['Approved dimensions, material and finish','Quantity and accessories match the order','Damage inspection before acceptance']},
  {id:'electronics',name:'Electronics & equipment',group:'Physical products',icon:'code',examples:'Computers, cameras, audio and business equipment',template:'goods',checks:['Model, serial number and condition recorded','Functional inspection against agreed tests','Accessories and warranty terms included']},
  {id:'fashion',name:'Fashion & accessories',group:'Physical products',icon:'design',examples:'Apparel, bags, handmade accessories',template:'goods',checks:['Size, material and condition agreed','Authenticity evidence where relevant','Return costs and inspection period agreed']},
  {id:'collectibles',name:'Art & collectibles',group:'Physical products',icon:'star',examples:'Original art, trading cards and collectibles',template:'goods',checks:['Ownership and provenance documented','Independent authentication if required','Insured packing and condition photographs']},
  {id:'wholesale',name:'Wholesale & manufacturing',group:'Physical products',icon:'brief',examples:'Batches, samples, custom production, supply orders',template:'procurement',checks:['Approved sample, specification and tolerances','Inspection method and named verifier agreed','Delivery responsibilities and shipping costs agreed']},
  {id:'development',name:'Developers & software',group:'Professional services',icon:'code',examples:'Websites, apps, APIs, integrations, maintenance',template:'development',checks:['Stage-specific acceptance tests','Repository access and source delivery','Deployment and credential handover']},
  {id:'marketing',name:'Marketing & creators',group:'Professional services',icon:'growth',examples:'Campaigns, content creation, disclosed sponsored posts',template:'marketing',checks:['Approved brief and required sponsorship disclosures','Publication URL and agreed live period','Deliverable evidence; no fabricated engagement']},
  {id:'creative',name:'Design, video & writing',group:'Professional services',icon:'design',examples:'Branding, video, motion, copywriting, translation',template:'service',checks:['Deliverable formats and revision count','Usage rights and licensed assets','Approved scope and deadline']},
  {id:'automation',name:'AI & automation',group:'Professional services',icon:'spark',examples:'Assistants, workflow integration and data tooling',template:'development',checks:['Agreed test data and success criteria','Error handling and human approval','Privacy and access scope documented']},
  {id:'local',name:'Local jobs & installations',group:'Professional services',icon:'home',examples:'Assembly, installation, repairs, photography',template:'service',checks:['Work location and scope confirmed privately','Completion checklist and photographs','Licences and insurance where necessary']},
  {id:'contracts',name:'Contracts & invoices',group:'Business agreements',icon:'write',examples:'Private agreements, retainers, B2B invoices',template:'contract',checks:['Named counterparties and fixed payment recipients','Deliverables, deadlines and dispute scope','Only funded milestones are protected']},
  {id:'real-estate',name:'Real estate escrow',group:'Business agreements',icon:'home',examples:'Residential, commercial and land purchase deposits with closing checklists',template:'real_estate',checks:['Fictional property reference and transaction type','Earnest deposit and cash-to-close amount are itemized','Inspection, financing, appraisal and title conditions are explicit','Closing date and settlement contact are recorded']},
  {id:'procurement',name:'Procurement & sourcing',group:'Business agreements',icon:'brief',examples:'Supplier orders, sample approvals and inspections',template:'procurement',checks:['Supplier identity and goods specification','Inspection evidence before each release','Returns, taxes and freight responsibilities']},
  {id:'events',name:'Events & bookings',group:'Business agreements',icon:'clock',examples:'Vendors, venues, catering and equipment bookings',template:'contract',checks:['Date, location and cancellation terms','Vendor deliverables and dependencies','Documented change and refund process']},
  {id:'deposits',name:'Deposits & holdbacks',group:'Business agreements',icon:'lock',examples:'Equipment deposits and performance holdbacks',template:'holdback',checks:['Objective conditions for deductions','Inspection and return deadline','Deposit is not insurance or a legal trust']},
  {id:'domains',name:'Domains & websites',group:'Digital handovers',icon:'globe',examples:'Transferable domains, websites and associated assets',template:'domain_sale',checks:['Seller control and transferability verified','Registrar, expiry and transfer lock disclosed','Domain transferred and buyer DNS control tested','No prohibited account, credential or trademark-infringing sale']},
  {id:'licenses',name:'Licences & source assets',group:'Digital handovers',icon:'download',examples:'Permitted code licences, design assets and project files',template:'handover',checks:['Seller owns transferable rights','Licence scope and permitted use agreed','Deliverables verified before acceptance']}
];
export const WORKFLOWS = [
  {id:'goods',name:'Product delivery',kind:'goods',description:'Fund, ship, receive, inspect, accept. Optional warranty holdback.',steps:['Agree on the product','Lock the payment','Ship with evidence','Buyer receives & inspects','Release or resolve'],questions:['Exact product, quantity and condition','Delivery area and deadline','Shipping price and taxes','Inspection window','Returns, costs and warranty']},
  {id:'development',name:'Development milestones',kind:'service',description:'Specification, implementation, testing and source-code handover.',steps:['Agree acceptance tests','Approve design','Review working build','Test & hand over','Release each milestone'],questions:['What must each stage deliver?','Which tests define completion?','How many revisions?','Who owns the source?','What support remains after release?']},
  {id:'marketing',name:'Campaign deliverables',kind:'service',description:'Pay for defined work and evidence—not promised token prices or invented engagement.',steps:['Approve campaign brief','Approve creative','Verify publication','Check reporting','Release payment'],questions:['Which channels and deliverables?','Who pays ad spend?','Required sponsorship disclosures?','How long must posts stay live?','What evidence counts as delivery?']},
  {id:'service',name:'Fixed-scope service',kind:'service',description:'Clear deliverables, revisions and acceptance checks.',steps:['Define done','Fund','Deliver','Review','Release'],questions:['What is included?','What is excluded?','Inputs required from the buyer?','Revision count?','Delivery deadline?']},
  {id:'contract',name:'Private contract',kind:'contract',description:'Bring an existing counterparty and turn the payment terms into milestones.',steps:['Name counterparties','Approve terms','Fund stages','Evidence & review','Release or renegotiate'],questions:['What obligation is being paid for?','Which stages are funded?','What is the governing agreement?','What happens on delay?','What can the resolver decide?']},
  {id:'real_estate',name:'Real estate escrow',kind:'real_estate',description:'Track an earnest-money deposit against due diligence and a documented closing checklist.',steps:['Record property & deposit','Approve contingencies','Fund earnest money','Complete title / closing checklist','Release or resolve'],questions:['What fictional property reference identifies the deal?','What is the purchase price and earnest deposit?','Which inspection, financing and appraisal contingencies apply?','Who is the settlement contact and when is closing targeted?','What conditions must be complete before release?']},
  {id:'procurement',name:'Manufacturing & supply',kind:'contract',description:'Sample, production, inspection and delivery milestones.',steps:['Approve specifications','Review sample','Verify inspection','Receive shipment','Close holdback'],questions:['Material and tolerance specifications?','Sample approval process?','Independent inspector?','Freight and tax responsibilities?','Defect and return remedy?']},
  {id:'holdback',name:'Warranty / deposit',kind:'contract',description:'Keep a specified balance available for agreed post-delivery obligations.',steps:['Define covered issues','Fund holdback','Start agreed period','Inspect outstanding issues','Release or dispute'],questions:['Which defects or deductions qualify?','How much remains locked?','When does the period start?','What is excluded?','What evidence is required?']},
  {id:'handover',name:'Digital asset handover',kind:'contract',description:'Verify transferable ownership, access and usage rights.',steps:['Verify rights','Fund','Transfer control','Buyer tests access','Release'],questions:['Is transfer allowed?','What assets are included?','What proves control?','Are there third-party consents?','What warranties are offered?']}
  ,{id:'domain_sale',name:'Domain sale escrow',kind:'domain_sale',description:'Buy or sell a domain with disclosed registrar terms, verified control, and a buyer DNS challenge before release.',steps:['Verify seller control','Agree price','Fund','Transfer or push domain','Buyer verifies DNS control','Release or resolve'],questions:['What is the normalized domain and registrar?','When does the registration expire and who renews it?','Which transfer method and included assets apply?','What proves seller control and buyer control?','What happens if a registrar lock or dispute prevents transfer?']}
  ,{id:'salary_disbursement',name:'Salary disbursement',kind:'payroll',description:'Plan fixed employee salaries from a monthly budget, approve one batch, or authorize a bounded pre-funded schedule.',steps:['Add staff','Set monthly budget','Allocate salaries','Review approval or autopay','Fund and authorize','Track receipts'],questions:['Which staff and verified payout wallets are included?','What is the monthly budget and total allocated?','Which asset, network, payday and timezone apply?','Is this one monthly approval or a bounded multi-month schedule?','What happens when a payment is late, blocked or needs to be paused?']}
];
export const PROHIBITED = ['Illegal or stolen goods','Weapons, controlled drugs and regulated hazardous items','Counterfeit goods and intellectual-property violations','Money laundering, sanctions evasion and payment laundering','Market manipulation, fake reviews, fake engagement or deceptive promotion','Unlicensed securities, gambling or regulated financial products','Accounts, personal data or credentials whose sale is prohibited','Sexual exploitation or adult services','Real-estate title custody or legal trust services without specialist approval'];
export const categoryById = id => TAXONOMY.find(c=>c.id===id);
export const workflowById = id => WORKFLOWS.find(c=>c.id===id);
